spring.application.name=smart-inventory
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/smart_inventory_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=3380437dulanka

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080
